# Generated by Django 5.1.4 on 2025-01-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_rename_categories_posteo_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='categorias',
        ),
        migrations.AddField(
            model_name='posteo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppBlog.categoria'),
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='autor',
        ),
        migrations.AddField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppBlog.autor'),
        ),
    ]
