# Generated by Django 5.1.4 on 2025-01-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_remove_posteo_categoria_posteo_categorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='categorias',
        ),
        migrations.AddField(
            model_name='posteo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppBlog.categoria'),
        ),
    ]
