# Generated by Django 5.1.4 on 2025-01-15 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_posteo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.autor'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.categoria'),
        ),
    ]
