# Generated by Django 5.1.4 on 2025-01-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_posteo_autor_alter_posteo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='id',
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
