# Generated by Django 5.1.4 on 2025-01-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_remove_posteo_categoria_delete_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posteo',
        ),
    ]
