# Generated by Django 5.1.4 on 2025-01-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='autor',
        ),
    ]
