# Generated by Django 5.1.4 on 2025-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0015_remove_posteo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='resumen',
            field=models.CharField(max_length=150),
        ),
    ]
