# Generated by Django 5.1.4 on 2025-01-26 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0016_posteo_imagen_alter_posteo_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
