# Generated by Django 5.1.4 on 2025-01-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0017_alter_posteo_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='imagen',
        ),
    ]
