# Generated by Django 5.1.4 on 2025-01-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0020_posteo_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
